
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD


#ifndef TAPPING_TERM

#    define TAPPING_FORCE_HOLD
#    define TAPPING_TERM 140
#    define TAPPING_TERM_PER_KEY
#    define IGNORE_MOD_TAP_INTERRUPT
#endif  // TAPPING_TERM
